version: '3.1'

services:

  service-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db-data: